name: Dockerfile

on:
  push:
    branches: [back-end]
    paths-ignore:
      - readme.md
      - .github/workflows/**

jobs:
  build:
    environment: back-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: create .env
        run: |
          touch .env
          echo 'BOOK_DB=${{ secrets.BOOK_DB }}' >> .env
          echo 'USER_DB=${{ secrets.USER_DB }}' >> .env 
          echo 'HISTORY_DB=${{ secrets.HISTORY_DB }}' >> .env 
          echo 'USER=${{ secrets.USER }}' >> .env 
          echo 'PASSWD=${{ secrets.PASSWD }}' >> .env 
          echo 'IP=${{ secrets.IP }}' >> .env 
          echo 'PORT=${{ secrets.PORT }}' >> .env 
          echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> .env 

      - name: check directory
        run: |
          ls -a

      - name: Docker Build
        run: |
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=lmao1415/ltw:latest -t lmao1415/ltw .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push lmao1415/ltw

  deploys:
    environment: back-end
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Deploy to Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-csnkdl0gph6c73bg3s1g/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "branch": "main",
                  "docker": true
                }'
      

